"""
Django settings for crm_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import os.path
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'users.apps.UsersConfig',
    'crm.apps.CrmConfig',
    'widget_tweaks',
    'django_filters',
    'debug_toolbar',
    'rest_framework',
    'drf_yasg',
    'axes',
    'admin_honeypot',
]

AUTHENTICATION_BACKENDS = [
    # Axes должен быть ПЕРВЫМ
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]


MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- НАСТРОЙКИ AXES (ВЫШИБАЛЫ) ---
AXES_FAILURE_LIMIT = 3          # 3 попытки - и бан
AXES_COOLOFF_TIME = 1           # Бан на 1 час
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True # Блокируем IP + Логин
AXES_RESET_ON_SUCCESS = True    # Если вошел правильно, счетчик сбрасывается

ROOT_URLCONF = 'crm_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# crm_project/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # Пароль не должен быть похож на имя пользователя
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    # Минимум 8 символов (лучше поставь 10 или 12)
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 10}},
    # Пароль не должен быть популярным (типа "password", "qwerty")
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    # Пароль не должен состоять только из цифр
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

# URL, на который будет перенаправляться пользователи,
# если они не авторизованы и пытается получить доступ к защищенной странице
LOGIN_URL = 'login'  # Имя URL-а из django.contrib.auth.urls

# URL, на который пользователь будет перенаправлен после
# успешного входа
LOGIN_REDIRECT_URL = 'crm:deal_list'  # Наш список сделок


# URL, на который пользователь будет перенаправлен после выхода
LOGOUT_REDIRECT_URL = 'login'  # Обратно на страницу входа


INTERNAL_IPS = [
    '127.0.0.1',
]
# --- ДОБАВЛЯЕМ ЭТОТ БЛОК ДЛЯ DOCKER ---
import socket

# Пытаемся получить IP адрес, с которого Docker стучится в контейнер
try:
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS += [ip[:-1] + '1' for ip in ips]
except Exception:
    pass
# --------------------------------------

# crm_project/settings.py

# --- НАСТРОЙКИ CELERY ---
REDIS_HOST = os.environ.get('REDIS_HOST', '127.0.0.1')

CELERY_BROKER_URL = f'redis://{REDIS_HOST}:6379/0'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:6379/0'
CELERY_timezone = 'UTC'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # Если ты в Docker, используй 'redis', если локально на Windows - '127.0.0.1'
        # Используем переменную окружения, как мы делали ранее:
        "LOCATION": f"redis://{os.environ.get('REDIS_HOST', '127.0.0.1')}:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
# --- НАСТРОЙКИ EMAIL (ДЛЯ ТЕСТА) ---
# Пока будем выводить письма В КОНСОЛЬ, чтобы не настраивать SMTP Google
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


REST_FRAMEWORK = {
    # 1. АУТЕНТИФИКАЦИЯ (Как система понимает, кто ты)
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication', # Использует вход через админку/сайт (Cookies)
        'rest_framework.authentication.BasicAuthentication',   # Позволяет передать логин/пароль в заголовке (для тестов)
    ],

    # 2. ПРАВА ДОСТУПА (Глобально)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # По умолчанию всё закрыто для чужаков
    ],

    # 3. ЗАЩИТА ОТ СПАМА И АТАК (Throttling) - Самое важное для безопасности
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle', # Ограничение для анонимов (хакеров)
        'rest_framework.throttling.UserRateThrottle'  # Ограничение для сотрудников
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/minute',    # Хакер сможет сделать только 5 попыток в минуту
        'user': '1000/day',    # Сотрудник может делать 1000 запросов в день (или '60/minute')
    },

    # 4. ПАГИНАЦИЯ (Чтобы не грузить базу, если сделок будет 10000)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10, # Показывать по 10 штук на странице

    # 5. ФОРМАТ ДАННЫХ
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',         # Для программ (чистый текст)
        'rest_framework.renderers.BrowsableAPIRenderer', # Для людей (красивый интерфейс в браузере)
    ]
}

# Эти настройки включаем ТОЛЬКО если DEBUG=False (то есть на реальном сервере)
if not DEBUG:
    # Защита от XSS и перехвата кук
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Куки только по HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Принудительный редирект на HTTPS
    SECURE_SSL_REDIRECT = True

    # HSTS (Говорит браузеру: "Заходи сюда только по HTTPS в следующий год")
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True