# Generated by Django 5.2.7 on 2025-11-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contract_name',
            new_name='contact_person',
        ),
    ]
